### ISSUE TITLE
Trilateration Between Phones

### ISSUE THREAD

**Issue by connorjoleary** [darryncampbell/WiFi-RTT-Trilateration#2]
Hey Darryn,

I'm hoping to adopt this same technology to use on an app which would calculate short range (<1000 m) map of multiple android phones. Do you think that this program could be adopted to work with multiple android phones, each with only rough estimates of where their individual locations are, so that as a group they could get fairly accurate information on where they are with respect to each other? Do you think I could do this with as little as three android devices?

**Comment by darryncampbell** [comment]
Hi @connorjoleary , you would still need access points that supported WiFi-RTT, you couldn't do it with just the mobile devices.
