### ISSUE TITLE
hello ineed help

### ISSUE THREAD

**Issue by YK7458** [darryncampbell/WiFi-RTT-Trilateration#3]
Hello, I want to ask a question about zebra development, I'm sorry, it's a little sudden, but I can't get help from others?
We are developing an OCR application based on Zebra Android PDA. We need to call the real-time preview imager of the imager and build a aiming box on it. However, I find that we cannot get the real-time preview image of the imager and build a aiming box. Please get your help.

**Comment by darryncampbell-pubnub** [comment]
Hi, I'm sorry but I haven't worked for Zebra for 2½ years now but back when I used to work on zebra OCR the underlying scanner framework had full control over the preview window and exposed only limited customisation, so what you're trying to do may not be possible. You may need to contact Zebra paid support for more up to date info

**Comment by YK7458** [comment]
> 你好，很抱歉，我已经两年半没有为 Zebra 工作了，但当我以前从事 Zebra OCR 工作时，底层扫描仪框架可以完全控制预览窗口，并且只提供有限的自定义功能，因此你尝试做的事情可能无法实现。你可能需要联系 Zebra 付费支持以获取更多最新信息

Thank you very much for your reply, but would like to ask you again how the limited customization functions are implemented and what steps can be taken

**Comment by darryncampbell-pubnub** [comment]
Please see here where I documented all I understood at the time: https://developer.zebra.com/blog/datawedge-ocr-what-it-and-how-control-it (this information may be out of date)

**Comment by YK7458** [comment]
> 请参阅此处，我记录了当时我所理解的一切： https: [//developer.zebra.com/blog/datawedge-ocr-what-it-and-how-control-it](https://developer.zebra.com/blog/datawedge-ocr-what-it-and-how-control-it)（此信息可能已过时）

Thank you very much.

**Comment by YK7458** [comment]
> 请参阅此处，我记录了当时我所理解的一切： https: [//developer.zebra.com/blog/datawedge-ocr-what-it-and-how-control-it](https://developer.zebra.com/blog/datawedge-ocr-what-it-and-how-control-it)（此信息可能已过时）

Thank you very much.
